### ISSUE TITLE
Cannot delete entries

### ISSUE THREAD

**Issue by gci2014** [5-star/plugin.video.last_played#11] opened 2020-12-20 12:29 UTC
When I try to delete a single entry from the playlist by pushing "Remove from list" over the desired item, I get "Last played error" (Check the log for more information). Tested on different systems (Windows and android) and I get the same problem. I can delete entire playlist by clicking "Delete Addon History List" (debug setting: ON), but I only want to delete individual entries.

**Comment by 5-star** [comment] 2020-12-20 14:29
It's fixed now on 6.0.1

It was caused by the changes to make it compatible with Kodi 19

**Closed by 5-star** 2020-12-20 14:29 UTC
